version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=test03_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql:rw
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/test03
    ports:
      - "10524:3000"
    depends_on:
      - db
    environment:
      DB_NAME: test03_db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
